# Importaciones

In [21]:
import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

import warnings
warnings.filterwarnings('ignore')

# Carga de datos

In [5]:
url = 'https://raw.githubusercontent.com/kaaiik/Airbnb-Predict/master/data/train.csv'
train = pd.read_csv(url, encoding='unicode_escape')
train.head(2)

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,https://www.airbnb.com/rooms/2842228,20211205213126,2021-12-06,Your little appartment on wheels,A waggon luxurous designed as a hotel room on ...,"Waterland is a beautiful countryside area, wit...",https://a0.muscache.com/pictures/cc2aa51a-3c11...,3040748,https://www.airbnb.com/users/show/3040748,Henk,2012-07-24,"Amsterdam, North Holland, The Netherlands","Living in the countryside, just near Amsterdam...",within a few hours,100%,75%,f,https://a0.muscache.com/im/users/3040748/profi...,https://a0.muscache.com/im/users/3040748/profi...,NaN,13,13,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,t,"Amsterdam, North Holland, Netherlands",Noord-Oost,NaN,52.39508,4.99186,Private room in farm stay,Private room,3,NaN,1.5 shared baths,1.0,NaN,"[""First aid kit"", ""Free parking on premises"", ...",87.0,2,1125,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,0,0,0,249,2021-12-06,81,0,0,2014-08-03,2019-06-15,4.62,4.56,4.29,4.57,4.75,4.69,4.49,0363 2A6D 7C09 877D 715F,f,10,0,10,0,0.91
1,1,https://www.airbnb.com/rooms/41236669,20211205213126,2021-12-06,Spacious 4p city center apartment (2 bedrooms!),Are you looking for a perfect place to stay in...,Our home is located in the Plantagebuurt. A un...,https://a0.muscache.com/pictures/5f33bf5a-399c...,34773624,https://www.airbnb.com/users/show/34773624,Julie,2015-06-01,"Amsterdam, Noord-Holland, Netherlands",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/a5da3...,https://a0.muscache.com/im/pictures/user/a5da3...,Weesperbuurt en Plantage,0,0,"['email', 'phone', 'reviews']",t,f,"Amsterdam, Noord-Holland, Netherlands",Centrum-Oost,NaN,52.36371,4.90745,Entire rental unit,Entire home/apt,4,NaN,1 bath,2.0,2.0,"[""Hot water kettle"", ""Pocket wifi"", ""Stove"", ""...",250.0,2,1125,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,3,3,3,3,2021-12-06,9,4,1,2020-01-26,2021-09-05,5.00,5.00,5.00,4.89,5.00,5.00,4.89,0363 BD0E 9934 ACCA D3DE,f,1,1,0,0,0.40

In [19]:
url2 = 'https://raw.githubusercontent.com/kaaiik/Airbnb-Predict/master/data/test.csv'
test = pd.read_csv(url2, encoding='unicode_escape')
test.head(2)

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,https://www.airbnb.com/rooms/43916178,20211205213126,2021-12-06,bright room to unplug and disconnect,this bright and quiet bedroom will offer you the peace and rest yo...,Amsterdam Oost is becoming every day a more cool and young neighbo...,https://a0.muscache.com/pictures/96d9838d-1200-4c9c-8641-7d8629f65...,9574877,https://www.airbnb.com/users/show/9574877,Filippo,2013-10-22,"Amsterdam, North Holland, Netherlands","I'm a young Italian designer with the passion for nature, food, c...",within an hour,100%,50%,f,https://a0.muscache.com/im/pictures/user/644927fe-e566-4002-8845-1...,https://a0.muscache.com/im/pictures/user/644927fe-e566-4002-8845-1...,NaN,1,1,"['email', 'phone', 'reviews', 'jumio', 'government_id']",t,t,"Amsterdam, Noord-Holland, Netherlands",Oud-Oost,NaN,52.35713,4.92470,Private room in rental unit,Private room,1,NaN,1 shared bath,1.0,1.0,"[""Hangers"", ""Drying rack for clothing"", ""Freezer"", ""Extra pillows ...",2,1125,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,29,59,89,89,2021-12-06,2,2,2,2021-11-16,2021-11-07,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0363 06C1 183D 5969 41C2,f,1,0,1,0,2.0
1,1,https://www.airbnb.com/rooms/45539504,20211205213126,2021-12-06,STAY CLOSE IN OUR SEMI-PRIVATE BUNK POD FOR 2,"BUNK Hotel Amsterdam is situated in the hip, up-and-coming neighbo...",Just minutes by free ferry from Central Station lies Amsterdam Nor...,https://a0.muscache.com/pictures/44c4cc8e-2dc5-424c-92bd-f7dfd1255...,243878598,https://www.airbnb.com/users/show/243878598,Bunk,2019-02-18,Netherlands,BUNK bridges the gap between hotels and hostels by combining affor...,within an hour,100%,100%,f,https://a0.muscache.com/im/pictures/user/f29b28aa-e5de-4c5f-971c-d...,https://a0.muscache.com/im/pictures/user/f29b28aa-e5de-4c5f-971c-d...,NaN,0,0,"['email', 'phone']",t,t,"Amsterdam, Noord-Holland, Netherlands",Oud-Noord,NaN,52.38810,4.91438,Shared room in hostel,Shared room,2,NaN,1 shared bath,1.0,1.0,"[""Building staff"", ""Wifi"", ""Long term stays allowed""]",1,365,1.0,3.0,999.0,999.0,1.0,999.0,NaN,t,0,0,5,280,2021-12-06,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Exempt,t,12,0,10,2,NaN

# Entrenamiento y test

In [9]:
import h2o
from h2o.automl import H2OAutoML

In [10]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.15" 2022-04-19; OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.18.04.1); OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.18.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.7/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpe31qg436
  JVM stdout: /tmp/tmpe31qg436/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpe31qg436/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ----------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.36.1.1
H2O_cluster_version_age:    21 days, 1 hour and 10 minutes
H2O_cluster_name:           H2O_from_python_unknownUser_bzm3gf
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.172 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.7.13 final
--------------------------  ----------------------------------

In [11]:
# parsear datos para h20

h2train=h2o.H2OFrame(train)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [12]:
X=[c for c in h2train.columns if c!='price']

y='price'

In [13]:
# inicia auto-machine-learning

automl=H2OAutoML(max_models=50,
                 seed=42,   # random_state
                 max_runtime_secs=300,
                 sort_metric='RMSE')

In [14]:
# entrena

automl.train(x=X,
             y=y,
             training_frame=h2train)

AutoML progress: |
16:43:31.134: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

████████████████████
16:45:06.128: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

██████████████
16:46:13.715: GLM_1_AutoML_1_20220504_164330 [GLM def_1] failed: DistributedException from /127.0.0.1:54321: 'Java heap space', caused by java.lang.OutOfMemoryError: Java heap space

█
16:46:15.970: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

█████
16:46:41.43: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

████████
16:47:18.540: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

███████████████| (done) 100%
Model Details
=============
H2OXGBoostEstimator :  XGBoost
Model Key:  XGBoost_1_AutoML_1_20220504_164330


Model Summary:

     number_of_trees
0              106.0

ModelMetricsRegression: xgboost
** Reported on train data. **

MSE: 213.71112914148375
RMSE: 14.618862101459325
MAE: 7.110540721323211
RMSLE: NaN
Mean Residual Deviance: 213.71112914148375

ModelMetricsRegression: xgboost
** Reported on cross-validation data. **

MSE: 10990.286032670498
RMSE: 104.83456506644409
MAE: 61.36444701115977
RMSLE: NaN
Mean Residual Deviance: 10990.286032670498

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,61.364372,3.897467,60.535534,62.499470,57.649870,67.494550,58.642440
1,mean_residual_deviance,10990.141000,2492.472200,11035.477000,11548.925000,9238.670000,14789.458000,8338.177000
2,mse,10990.141000,2492.472200,11035.477000,11548.925000,9238.670000,14789.458000,8338.177000
3,r2,0.457245,0.320012,0.337506,0.807539,0.304157,0.769333,0.067690
4,residual_deviance,10990.141000,2492.472200,11035.477000,11548.925000,9238.670000,14789.458000,8338.177000
5,rmse,104.311870,11.682020,105.049870,107.465930,96.118004,121.611916,91.313614
6,rmsle,NaN,0.000000,NaN,NaN,NaN,NaN,NaN

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2022-05-04 16:44:51,1 min 20.790 sec,0.0,246.805956,168.177946,60913.179686
1,,2022-05-04 16:44:53,1 min 22.098 sec,5.0,141.678450,46.660588,20072.783075
2,,2022-05-04 16:44:53,1 min 22.653 sec,10.0,112.947175,36.608842,12757.064233
3,,2022-05-04 16:44:54,1 min 23.203 sec,15.0,92.998288,33.570545,8648.681542
4,,2022-05-04 16:44:54,1 min 23.767 sec,20.0,82.675484,30.374990,6835.235687
5,,2022-05-04 16:44:55,1 min 24.325 sec,25.0,73.121757,27.833557,5346.791416
6,,2022-05-04 16:44:55,1 min 24.853 sec,30.0,63.030860,25.815453,3972.889318
7,,2022-05-04 16:44:56,1 min 25.420 sec,35.0,56.082686,23.856510,3145.267645
8,,2022-05-04 16:44:57,1 min 25.968 sec,40.0,50.878099,21.972502,2588.580929
9,,2022-05-04 16:44:57,1 min 26.519 sec,45.0,46.618330,20.513938,2173.268668
10,,2022-05-04 16:44:58,1 min 27.093 sec,50.0,41.261968,19.161397,1702.549968
11,,2022-05-04 16:44:58,1 min 27.703 sec,55.0,36.736594,17.505836,1349.577332
12,,2022-05-04 16:44:59,1 min 28.328 sec,60.0,33.513342,16.053347,1123.144061
13,,2022-05-04 16:45:00,1 min 28.988 sec,65.0,30.080127,15.117267,904.814039
14,,2022-05-04 16:45:00,1 min 29.748 sec,70.0,26.927666,13.613367,725.099173
15,,2022-05-04 16:45:01,1 min 30.415 sec,75.0,24.038741,12.546410,577.861072
16,,2022-05-04 16:45:02,1 min 31.020 sec,80.0,21.361464,11.146841,456.312148
17,,2022-05-04 16:45:02,1 min 31.664 sec,85.0,19.650218,10.074129,386.131080
18,,2022-05-04 16:45:03,1 min 32.251 sec,90.0,18.343091,9.188152,336.469001
19,,2022-05-04 16:45:03,1 min 32.823 sec,95.0,17.150844,8.538008,294.151436

See the whole table with table.as_data_frame()

Variable Importances:

,variable,relative_importance,scaled_importance,percentage
0,availability_365,27426504.00,1.000000,0.116755
1,last_review,15980639.00,0.582671,0.068030
2,availability_30,15614528.00,0.569323,0.066472
3,accommodates,12112514.00,0.441635,0.051563
4,host_neighbourhood.Nieuwmarkt en Lastage,11088665.00,0.404305,0.047205
5,calculated_host_listings_count_private_rooms,10690450.00,0.389785,0.045510
6,longitude,10610002.00,0.386852,0.045167
7,host_id,10438589.00,0.380602,0.044437
8,bedrooms,9499547.00,0.346364,0.040440
9,availability_60,8785518.00,0.320329,0.037400
10,first_review,8431888.00,0.307436,0.035895
11,review_scores_cleanliness,5513205.00,0.201017,0.023470
12,number_of_reviews_ltm,4754526.00,0.173355,0.020240
13,maximum_minimum_nights,4645308.00,0.169373,0.019775
14,review_scores_value,4432841.00,0.161626,0.018871
15,minimum_minimum_nights,4323559.00,0.157642,0.018406
16,availability_90,3639006.25,0.132682,0.015491
17,review_scores_location,3405287.50,0.124160,0.014496
18,minimum_maximum_nights,3161214.00,0.115261,0.013457
19,host_location.NL,3088213.00,0.112600,0.013147

See the whole table with table.as_data_frame()

In [15]:
print('[INFO] Leader board:')

leader_board=automl.leaderboard

leader_board.head()

[INFO] Leader board:

model_id,rmse,mse,mae,rmsle,mean_residual_deviance
XGBoost_1_AutoML_1_20220504_164330,104.835,10990.3,61.3644,nan,10990.3
XGBoost_2_AutoML_1_20220504_164330,112.059,12557.3,60.2786,nan,12557.3
GBM_1_AutoML_1_20220504_164330,158.298,25058.4,54.0491,0.437205,25058.4

In [22]:
# prediciones del lider
h2test=h2o.H2OFrame(test)

y_pred=automl.leader.predict(h2test)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
xgboost prediction progress: |███████████████████████████████████████████████████| (done) 100%

In [32]:
lst_pred = h2o.as_list(y_pred)
lst_pred

         predict
0      20.431084
1      54.277081
2     109.404915
3     144.424927
4     189.545792
...          ...
1384   46.598175
1385  127.410683
1386  185.545029
1387   76.973076
1388  125.432243

[1389 rows x 1 columns]

In [34]:
sample = pd.read_csv('https://raw.githubusercontent.com/kaaiik/Airbnb-Predict/master/data/sample.csv', encoding='unicode_escape')
sample.head()

   price  id
0      0   0
1      0   1
2      0   2
3      0   3
4      0   4

In [37]:
sample.price = lst_pred

In [41]:
mod1 = sample
mod1.head()

        price  id
0   20.431084   0
1   54.277081   1
2  109.404915   2
3  144.424927   3
4  189.545792   4

In [45]:
mod1.to_csv('prediccion.csv', index=False)

In [48]:
from google.colab import files
files.download('prediccion.csv')